### ISSUE TITLE
Labyrinth Spawning on top of other map buildings

### ISSUE THREAD

**Issue by ReDBaroN1** [worldwidesorrow/Epoch-Server-Events#1]
Hey Jason, love what you've done to these to tidy them up. I was running the original code with some of my own modifications dating back to 2014!! :)

Just testing them at the moment and set them to spawn every 3 mins for testing. The labyrinth spawned on the NEAF without any regard to existing buildings/structures that are already there. So, the end result is that it spawned with the fire station at NEAF in the middle of the labyrinth buildings and effectively closed parts of the maze off.
![labyrinth](https://user-images.githubusercontent.com/8584143/50287799-e01c5900-045b-11e9-9630-9e6780a6c9b0.jpg)

It's odd considering you have findsafepos in there....
`// Random location
_position = [getMarkerPos "center",0,(((getMarkerSize "center") select 1)*0.75),10,0,.2,0] call BIS_fnc_findSafePos;
`

**Comment by worldwidesorrow** [comment]
The 4th parameter is distance from objects. It is only set to 10. Increasing that would probably fix it. I increased it to 100 in the example below.

_position = [getMarkerPos "center",0,(((getMarkerSize "center") select 1)*0.75),100,0,.2,0] call BIS_fnc_findSafePos;

**Comment by ReDBaroN1** [comment]
Thanks for the reply.

Yeah, I read that and tried 150 and it didn't help. Also read on the wiki that anything over 10 will lag out a fair bit.  

I think this may have something to do with additional buildings spawned server side. As in it's just not recognising them. But, then I thought I saw it also happen at the fuel station on the road up to Klen Trader which is map based......so, testing more.

...confused atm. Not sure why even at 10 it's not working if it's not only happening on additional buildings.

**Comment by ReDBaroN1** [comment]
Hey man, just tested again and same problem. Nothing to do with my spawned in buildings, happens on normal Arma map buildings as you can see from the pics.

This is the line I'm currently using for safepos which, is the same as your example. Tried 150 as well.

`_position = [getMarkerPos "center",0,(((getMarkerSize "center") select 1)*0.75),100,0,.2,0] call BIS_fnc_findSafePos;
`
Stumped. Spoke with Salival (@oiad) and he suggested the same as you.....
![labyrinth_novy](https://user-images.githubusercontent.com/8584143/50317122-dc1b2600-04b1-11e9-9d7a-8c36a1979900.jpg)
![labyrinth_novy2](https://user-images.githubusercontent.com/8584143/50317124-dde4e980-04b1-11e9-89a9-b76549ee2c47.jpg)

**Comment by ReDBaroN1** [comment]
Just for additional info.... that change to 100 has definitely done something as now I have 6 on the map but 5 are on the exact same spot in Novy. You can see from the circle getting much more yellow...

I set only labyrinth to spawn and every 3 minutes for testing

![labyrinth_novy3](https://user-images.githubusercontent.com/8584143/50317510-dc1c2580-04b3-11e9-95c9-3fe5dddf79fe.jpg)

**Comment by oiad** [comment]
If it's spawning in novy it's failing to find a position since novy is map center.

Jason, I have code to do a loop to find a safe position I can share

**Comment by worldwidesorrow** [comment]
_position = [0,0,0];
	
while {count _position > 2} do { 
	_position = [getMarkerPos "center",0,(((getMarkerSize "center") select 1)*0.75),30,0,.2,0] call BIS_fnc_findSafePos;
};

Something like this.

**Comment by ReDBaroN1** [comment]
Thanks guys, I'll spin this up now and let you know how it goes.

**Comment by ReDBaroN1** [comment]
Thanks again chaps, it's definitely fixed the issue of spawning on buildings and only spawning in the centre of the map but, now they do seem to be clustered in the North West quadrant of the map. Pic below.

With that new code, I may try and bring the object distance number down a bit and see what it does unless you guys suggest something different.
![labyrinth_novy4](https://user-images.githubusercontent.com/8584143/50333480-676dd900-04fd-11e9-8c98-381317d28e99.jpg)

**Comment by ReDBaroN1** [comment]
@worldwidesorrow @oiad thanks for your help guys. Just to confirm the latest code above works. However, it seems to work best in terms of spreading across the map when you use 20 and haven't seen one collide with a building yet.

They do seem to disregard roads which is understandable and to be honest, I'm still thinking whether I actually like it that way.

**Comment by worldwidesorrow** [comment]
The position checks in the events are basic. They were originally designed to spawn in one at a time. WAI and DZMS have more checks to make sure that missions don't spawn on top of each other and are more spread out. In order to get the event positioning to behave like WAI, there would have to be a more elaborate position checking system like this:

https://github.com/worldwidesorrow/WICKED-AI/blob/master/WAI/compile/find_position.sqf

**Comment by ReDBaroN1** [comment]
Thanks @worldwidesorrow I think they're fine as they are now. Have found another issue which I'll start a different issue for.
