### ISSUE TITLE
Server.rpt error on Abandoned Vaults

### ISSUE THREAD

**Issue by ReDBaroN1** [worldwidesorrow/Epoch-Server-Events#2]
Hi again,

Just noticed this error:
`21:15:03 Error in expression <t getVariable ["CharacterID", "0"];
if (_code == "0000") then {
_vaults set [cou>
21:15:03   Error position: <_code == "0000") then {
_vaults set [cou>
21:15:03   Error Undefined variable in expression: _code
21:15:03 File z\addons\dayz_server\modules\abandoned_vaults.sqf, line 31
`
This is the block around line 31. Which seems to be defined....?
`for "_i" from 0 to (count _allvaults)-1 do {
	_current = _allvaults select _i;
	_code = _current getVariable ["CharacterID", "0"];
	if (_code == "0000") then {
		_vaults set [count _vaults, _current];
	};
};
`

**Comment by worldwidesorrow** [comment]
Looking over the code, I can't see why it would give that error. That being said we can get rid of the variable all together and just put the check on one line.

if ((_current getVariable ["CharacterID", "0"]) == "0000") then {

**Comment by ReDBaroN1** [comment]
@worldwidesorrow Thanks and sorry for the delay replying, I've been away for Christmas.

I'll try that and feedback here.

**Comment by ReDBaroN1** [comment]
Thanks, that seems to have fixed it. Haven't seen the error since.
