### ISSUE TITLE
Undefine Variable DZE_LockedSafes need change in abandoned_vaults.sqf

### ISSUE THREAD

**Issue by TheFirstNoob** [worldwidesorrow/Epoch-Server-Events#6]
In Epoch Variable doesnt exist DZE_LockedSafes. Think need change to DZE_LockedStorage
Dont forget change Variable on "Spectial instruction".

And u can add new epoch Safes

VaultStorageLocked","VaultStorage2Locked","LockboxStorageLocked","LockboxStorage2Locked","LockboxStorageWinterLocked","LockboxStorageWinter2Locked","TallSafeLocked

**Comment by AirwavesMan** [comment]
You did not read the install instructions to the end. The variable gets defined within the server_monitor. Also this script is just for Safes not for Lockboxes.

https://github.com/worldwidesorrow/Epoch-Server-Events/blob/master/modules/abandoned_vaults.sqf#L93

**Comment by TheFirstNoob** [comment]
ok. i recheck again my files. thx
